# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: en-GB
reviews:
  profile: assertive
  high_level_summary: false
  high_level_summary_in_walkthrough: false
  collapse_walkthrough: true
  changed_files_summary: false
  sequence_diagrams: false
  poem: false
  review_status: false
  commit_status: true
  request_changes_workflow: false
  auto_review:
    enabled: true
    drafts: false
  pre_merge_checks:
    docstrings:
      mode: off
    title:
      mode: off
    description:
      mode: off
chat:
  auto_reply: false
