---
k8s_version: "1.33"
k8s_package_version: "1.33.*"
pod_cidr: "10.244.0.0/16"
service_cidr: "10.96.0.0/12"
calico_version: "v3.30.2"
containerd_channel: "stable"
metallb_chart_version: "0.16.1"
traefik_chart_version: "41.4.0"
nfs_provisioner_chart_version: "4.0.18"
metrics_server_chart_version: "3.14.0"
kubelet_csr_approver_chart_version: "1.2.15"
metallb_pool_range: "192.168.122.200-192.168.122.220"
nfs_server: "192.168.122.230"
nfs_path: /data
