---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-registry
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.122.230
    path: /data/registry

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-data
  namespace: registry
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: nfs-registry
  resources:
    requests:
      storage: 20Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-grafana
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.122.230
    path: /data/grafana

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-nfs
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: nfs-grafana
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-vaultwarden
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.122.230
    path: /data/vaultwarden

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-nfs
  namespace: vaultwarden
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: nfs-vaultwarden
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-portainer
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.122.230
    path: /data/portainer

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portainer-nfs
  namespace: portainer
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: nfs-portainer
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-loki
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.122.230
    path: /data/loki

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-loki-0
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: nfs-loki
  resources:
    requests:
      storage: 10Gi
